### ISSUE TITLE
Crashing Server on 1.17.1

### ISSUE THREAD

**Issue by itsdinkd** [TheIllusiveC4/Polymorph#100]
https://pastebin.com/AbFwrBpP

Something strange is going on with Polymorph

**Comment by TheIllusiveC4** [comment]
I'll need more information. What happened that caused the crash? It looks like this was from someone attempting to craft something. Are you able to reproduce the issue? If so, please list out the steps.

**Comment by itsdinkd** [comment]
I'm not entirely sure. I went through crash logs on the server and saw this. However, I have been getting so many reports for weeks now that Polymorph doesn't work on the dedicated servers we run for our modpack, AQM2.

**Comment by TheIllusiveC4** [comment]
> I'm not entirely sure.

Then I'm a bit stuck on this issue. It works in my own testing, and I can't find the issue from the crash log. While it does have Polymorph in the stacktrace, Polymorph is just redirecting to a vanilla method where it's actually crashing. And it's crashing from the watchdog killing the server, so I can only assume it has something to do with the server taking too long to perform the task. However, I don't know what could be causing that since, like I said, Polymorph just redirects to the vanilla recipe logic.

>  However, I have been getting so many reports for weeks now that Polymorph doesn't work on the dedicated servers we run for our modpack, AQM2.

Is this related to this specific crashing? If not, you should open up new bug reports for those issues with detailed description, version numbers, and reproduction steps. Otherwise, I don't have enough information to act on them.

**Comment by TheIllusiveC4** [comment]
I'm unfortunately still not sure what the cause of this issue was but I rewrote a lot of the mod in the latest update so try that out and let me know if any more errors of this nature still occur.
