### ISSUE TITLE
Server crash report with Polymorph and Refined Storage

### ISSUE THREAD

**Issue by Victor-Noli** [TheIllusiveC4/Polymorph#102]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.5-0.27.jar
* Forge/Fabric: forge 36.2.9
#### Steps to Reproduce:
 Update polymorph.

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/PR6FBHQ8

**Comment by djoveryde** [comment]
Having the same issue after updating to the latest version of Polymorph. Server starts up fine and then just hangs to the point that the player numbers when pinging the server responds with ??? and then just causes the server to shut down due to hanging.

UPDATE: 0.25 works fine. 0.26 and 0.27 have the same issue.

**Comment by TheIllusiveC4** [comment]
I can't reproduce this issue, so it might take some time for me to figure out what's going on. I have some idea, because this happened during testing at some point before I implemented a solution, but I'm not sure why it would still be happening.

Current workaround: Disable the Refined Storage integration by going to your `config` folder, locating `polymorph-integrations.toml` and set `refinedstorage = false`. This will disable the integration and probably let you load your world at least.

**Comment by djoveryde** [comment]
Ok thankyou, not sure if it helps but when the server crashed it did generate a crash report, not sure if its identical to the OP, but always good to have multiple crash reports.
https://pastebin.com/Zi1u4tJs

**Comment by TheIllusiveC4** [comment]
Alright, I'll need some help from you two since you're encountering the error and I'm not. Can you use this test build of Polymorph with Refined Storage and see if it fixes the issue:
[polymorph-forge-1.16.5-0.28-SNAPSHOT20211107.zip](https://github.com/TheIllusiveC4/Polymorph/files/7493238/polymorph-forge-1.16.5-0.28-SNAPSHOT20211107.zip)

Make sure to re-enable the integration in the config if you disabled it as mentioned in my previous comment.

**Comment by djoveryde** [comment]
I'll add it in now and test it

**Comment by djoveryde** [comment]
Pleased to report it is now working. No crashes when I log in.
Servers been running stable for 5 minutes now.
