### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by shiskibab** [TheIllusiveC4/Polymorph#154]
I when i launch my pack it just crashed and says 
The game crashed whilst rendering overlay
Error: java.lang.IllegalAccessError: class net.minecraft.client.resources.language.LanguageManager tried to access private field net.minecraft.client.resources.language.ClientLanguage.f_118910_ (net.minecraft.client.resources.language.LanguageManager and net.minecraft.client.resources.language.ClientLanguage are in module minecraft@1.18.1 of loader 'TRANSFORMER' @158ae284)
Exit Code: -1
im running forge 39.0.8+
IT only happens when polymorph is on if i remove IT the modpack starts fine

**Comment by TheIllusiveC4** [comment]
Please fill out the bug report template. You need to at least give me the Polymorph version and the full crash log. If you don't know where that is, it's in the `crash-reports` folder of your instance folder. Without a full crash log, I can't tell anything because the snippet you posted doesn't point to Polymorph anywhere.

Edit: Also, your Forge version is quite old, try updating it as well and see if it fixes your issue.

**Comment by shiskibab** [comment]
what template ? 
im useing forge 39.1.2
and polymorph 0.39
[crash-2022-03-02_11.48.52-client.txt](https://github.com/TheIllusiveC4/Polymorph/files/8168965/crash-2022-03-02_11.48.52-client.txt)

**Comment by TheIllusiveC4** [comment]
```
at net.minecraft.client.resources.language.LanguageManager.handler$zln000$onResourceManagerReload_HammerLib(LanguageManager.java:528)
```

From your crash report, it looks like it's an issue with some mod called HammerLib. Try either updating the mod, re-installing it, or reporting this to the developer.
