### ISSUE TITLE
Low performance in 1.18.2 Arclight Modded server.

### ISSUE THREAD

**Issue by qyl27** [TheIllusiveC4/Polymorph#161]
I tried to re-add the Polymorph mod into my server, but I found the performance issue is still here (or a new issue).

#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.18.1-0.40
* Forge/Fabric: 40.0.32

#### Steps to Reproduce:
Install Polymorph and login to the server, play as normal.

#### More Info
Minecraft: 1.18.2
Server version: arclight-1.18.2-1.0.2-SNAPSHOT-ae3ff3d1
Spark report: https://spark.lucko.me/AbbCdYGNuJ

**Comment by TheIllusiveC4** [comment]
That's a little weird because now the profiling is showing that something else is causing performance issues which wasn't doing that in the last report. I'm not sure why that changed suddenly.

Anyways, this time I've tried to tackle this a little more aggressively from 3 different angles. Performance should be improved by at least 5 times, if not more. Please try out the new 1.18.1-0.41 version and let me know if there continues to be performance issues.
