### ISSUE TITLE
1.19.2 - Server Side Crash/Hang with mods (``Polymoprh, Visual Workbench``)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheIllusiveC4/Polymorph#192]
https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/17

**Comment by TheIllusiveC4** [comment]
How do you know that this is a Polymorph issue? Polymorph has no known interaction between those mods and I cannot see Polymorph mentioned anywhere in the log attached to the issue you linked.

**Comment by P3rf3ctXZer0** [comment]
Damn that is the wrong log - one second.

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/5de2460668ec14677b645e7fa99b5927

(Accidentally posted wrong log.)

Crashlog 

https://gist.github.com/P3rf3ctXZer0/cb17b598ad17aa4ac3118c5734be48b3

**Comment by TheIllusiveC4** [comment]
Hmm, I'm not sure exactly what's going wrong here but I don't think it's related to Visual Workbench or Polymorph. Those mods are just calling regular vanilla methods near the top of their respective stacktrace sections. I would suspect Bigger Stacks may be interfering with the Ingredient initialization somehow but that's just a guess based purely on how extensively they seem to modify the base game.

I suggest removing Bigger Stacks and see if the crash/hang still occurs. If it does, try removing all other mods and isolating which of these mods specifically cause the issue to occur.

**Comment by P3rf3ctXZer0** [comment]
Yeah that was the next plan. I close this till I get more info.

**Comment by P3rf3ctXZer0** [comment]
The JEI devs said it is polymorph. 
![LtIgz6F 1](https://user-images.githubusercontent.com/10351221/198918939-4a3bb14c-1dc1-4dab-9f69-7915f84d077c.png)

**Comment by mezz** [comment]
I actually have no idea what mod is causing the issue yet, I only looked into it enough to rule out JEI.
The JEI issue was opened here: https://github.com/mezz/JustEnoughItems/issues/3028

**Comment by mezz** [comment]
@P3rf3ctXZer0 it looks like you will need to narrow this down by removing mods until the issue goes away. 
If you can figure out exactly which mods are involved in the bug, you can make a more actionable bug report.

**Comment by TheIllusiveC4** [comment]
> it looks like you will need to narrow this down by removing mods until the issue goes away.
If you can figure out exactly which mods are involved in the bug, you can make a more actionable bug report.

I agree with this suggestion. It's necessary to reproduce this issue with the minimal number of mods involved before we can begin to figure out where it's going wrong.

I'll also clarify that I never said it wasn't Polymorph, I just don't _think_ it is from what the stacktrace tells me. The point that's crashing from Polymorph's end is simply a call to the vanilla recipe manager's `getRecipesFor` method so I don't know why it would cause this crash on its own. I also doubt it's JEI + Polymorph together somehow because I'd wager almost all instances of Polymorph are running JEI as well and this is the first report I've heard of this crash.

I would suggest OP to try and reproduce this with only JEI, Polymorph, Visual Workbench, and Bigger Stacks and see if this happens again. If it does, continue isolating each mod from each other until you find which mod or combination of mods cause the issue consistently. If it doesn't, then you'll need to extend your search to the other mods in your instance as well.

**Comment by P3rf3ctXZer0** [comment]
I mean I did that with no crashing so it definitely is a mod conflict. Unfortunately I don't have time to deal with it. Also my pack has changed dramatically since posting this issue. If it is not relevant or you are unable to deal with it I will simply close this issue as I have long since removed polymorph and kept visual workbench and have had absolutely no issues.
