### ISSUE TITLE
ServerHangWatchdog detected that a single server tick took 60.00 seconds

### ISSUE THREAD

**Issue by jaynotgay** [TheIllusiveC4/Polymorph#212]
#### Versions (Be specific, do not write "latest"):
* Polymorph:  polymorph-forge-0.46.1+1.19.2
* Forge
#### Steps to Reproduce:  
1. Happens randomly a couple times per day.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

https://hastebin.com/share/huyobufago.bash
https://hastebin.com/share/kifojuredo.bash
https://hastebin.com/share/ileyiciyej.bash

**Comment by TheIllusiveC4** [comment]
I'm not sure Polymorph is the main culprit based on the stacktrace. Does this happen if you remove Polymorph?

**Comment by jaynotgay** [comment]
https://spark.lucko.me/lxrSTNUwgL

![polymorth](https://user-images.githubusercontent.com/30220126/231600562-060ec901-bdcc-4311-b0bd-9066e12b3e05.png)

**Comment by TheIllusiveC4** [comment]
Polymorph wraps the vanilla recipe functions, which is where you can see most of the performance is impacted from through `RecipeManager.getRecipesFor()`. Which is why I'm asking if this happens if you remove Polymorph, because it could be a result of the recipes in your environment rather than Polymorph itself.

If it doesn't happen without Polymorph, then we can move on to other follow-up questions but I need to verify that fact first.

**Comment by jaynotgay** [comment]
The issues occur in the modpack FTB Skies and was also happening in the modpack ATM8 

we run a wet work of servers

**Comment by TheIllusiveC4** [comment]
Regardless of which modpack it is in, you need to verify first whether the issue occurs without Polymorph installed. Otherwise, I cannot be certain of the cause.

**Comment by jaynotgay** [comment]
Do you have any idea what else would be causing it? Or any idea of what I’d making poly morth to do this?

**Comment by TheIllusiveC4** [comment]
I don't have much to go on, unfortunately. My best guess is that it seems like something is causing the recipe matching to take longer than necessary, but that could be due to any number of reasons. It's difficult to grasp because much of the information is obfuscated behind vanilla recipe functions.
