### ISSUE TITLE
[Bug]: Polymorph doesn't function anymore when Fast Workbench / Fast Furnace is installed alongside it.

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/Polymorph#234]
### Minecraft Version

1.20.1

### What happened?

Polymorph doesn't function anymore when Fastworkbench & FastFurnace is installed.

1. If Fast Furnace is installed, smelting recipe conflicts doesn't show the Polymorph button.
2. If Fast Workbench is installed, crafting table recipe conflicts doesn't show the Polymorph button.

### How do you trigger this bug?

1. Install Polymorph
2. Install Fast Workbench / Fast Furnace
3. Polymorph doesn't function anymore. (Button doesnt show for recipe conflicts)
Profit.

### Loader

Forge

### Loader Version

47.1.3

### API Version

N/A

### Mod Version

0.49.0

### Relevant Log Outputs

Here: https://gist.githubusercontent.com/Gbergz/06c06d3d9cb3f4d64fe6c8b6e3e24c35/raw/53eeca595e1f5f2ad63414ae6335a339991ee42e/gistfile1.txt

**Other**
Mods installed:
![screen](https://github.com/illusivesoulworks/polymorph/assets/26634554/1410fc17-832f-43f3-85c4-c76212639c68)

**Comment by skybix** [comment]
I have the same problem using Forge-47.2.1

**Comment by drakray** [comment]
Still exist in 1.20.1 with NeoForge 47.1.79, is there any plans to fix compat, or to implement a variant directly in Polymorph to not need FastWorkbench/FastFurnace?

**Comment by Shadows-of-Fire** [comment]
Mixin targets are outdated:
https://github.com/illusivesoulworks/polymorph/blob/1.20.x/forge/src/main/java/com/illusivesoulworks/polymorph/mixin/integration/fastbench/PolymorphMixinFastBenchUtil.java#L31
https://github.com/illusivesoulworks/polymorph/blob/1.20.x/forge/src/main/java/com/illusivesoulworks/polymorph/mixin/integration/fastsuite/PolymorphMixinAuxRecipeManager.java#L31

These are still using 1.19.x code, the files are no longer located in `shadows.*` and are in `dev.shadowsoffire.*`:
https://github.com/Shadows-of-Fire/FastWorkbench/blob/1.20/src/main/java/dev/shadowsoffire/fastbench/util/FastBenchUtil.java
https://github.com/Shadows-of-Fire/FastSuite/blob/1.20/src/main/java/dev/shadowsoffire/fastsuite/AuxRecipeManager.java

Additionally my projects are now available via https://maven.shadowsoffire.dev/#/releases/dev/shadowsoffire instead of only being available via CurseMaven.

**Comment by TheIllusiveC4** [comment]
Polymorph should now be able to work with all/any of the Fast mods as of version 0.49.2.
