### ISSUE TITLE
Recipe switching "failure" possible cause?

### ISSUE THREAD

**Issue by Barking3086** [TheIllusiveC4/Polymorph#235]
Not sure whether to do this as a bug or feature request, but:

Along with a number of other people. I have been having the issue of recipes appearing not to switch while using Polymorph on 1.20.1 (Forge). However, I just discovered that whilst using "Visual Workbench", if you select the alternative recipe and then exit the crafting interface, when you reopen the crafting table interface the recipe HAS changed to the selected alternative. Not sure if this is the cause of all of the times Polymorph "seems" to fail, but I thought it might help diagnose the problem, or at least narrow the search somewhat.

**Comment by forthwist** [comment]
Confirmed!  We also discovered this on our server.  Been a decent workaround for now

**Comment by TheIllusiveC4** [comment]
Unfortunately, I am unable to reproduce this. With just Visual Workbench and Polymorph installed, the recipe switching works as intended. Unless your environment only had these two mods installed, it's likely that this is caused by an unidentified 3rd mod causing a conflict. I would suggest first testing Visual Workbench and Polymorph (and the mods needed to produce a recipe conflict) on their own to verify this, and then proceed to search for the mod that _is_ causing this behavior to occur.

**Comment by Barking3086** [comment]
Yeah, as far as I can tell whatever was preventing the recipe selection from updating was fixed somewhere in the seven months since I submitted this report. I apologise for not closing this earlier, it kind of slipped my mind.
