### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rose-Magnus** [TheIllusiveC4/Polymorph#252]
### Minecraft Version

1.20.1

### What happened?

when trying to craft fireworks i found it fails to properly offer up all flight power options. so if you have 2 gunpowder in the crafting grid with 1 paper it will not offer flight power 2 it will only show flight power 1 everytime even on flight power 3 on 1.20.1 from what i see.

### How do you trigger this bug?

1.loads up with mod
2.has gunpowder and paper
3. go into valid crafting bench for polymorph
4. insert craft for the flight fireworks with flight level 2 or higher
5. bug is encountered upon trying to choose the correct output
...

### Loader

Fabric

### Loader Version

0.15.3

### API Version

0.91.0+1.20.1

### Mod Version

0.49.1+1.20.1

**Comment by TheIllusiveC4** [comment]
I am unable to reproduce this, placing 2 gunpowder and 1 paper properly results in Flight Duration: 2 rockets as expected. It also works with Flight Duration: 3 as expected. I would suggest trying to reproduce this with _just_ Polymorph installed in order to verify if this is a mod conflict. If it is, the mod in question would also need to be identified.
