### ISSUE TITLE
[Feature]: Config File for "common crafting tables"

### ISSUE THREAD

**Issue by IttoSanzzo** [TheIllusiveC4/Polymorph#257]
### What is the new feature or improvement?

Just like, Visual Workbench works, would it be viable to make a config file for the mod, that a user can write "simple workbenches" item ids, and if they function the same as the vanilla's one, it would make the mod appear on them. Just a simple suggestion, I really don't know how viable it could be. Thanks.

**Comment by TheIllusiveC4** [comment]
This is already how Polymorph works underneath the hood for "basic" crafting tables. But sometimes a mod can look the same as the vanilla one but function quite differently code-wise, which Polymorph won't pick up without proper integration. And it's unfortunately not really viable to try and abstract this into a way that's universally applicable since there's no standardized way that crafting screens are done.
