### ISSUE TITLE
[Bug]: Showing both recipes but will only craft one of them even with the second selected.

### ISSUE THREAD

**Issue by MrSickNSinister** [TheIllusiveC4/Polymorph#266]
### Minecraft Version

1.20.1

### What happened?

Trying to smelt "Simple Animated Guns" plastic with "Croptopia" installed, expected furnace to smelt simple animated guns plastic. Showing both recipes but forces croptopia molasses to smelt even with simple animated guns plastic selected. 

### How do you trigger this bug?

1.Insert "Sugar Cane" into furnace, select "plastic", smelt.
2.Outputs as "Molasses"
3.
...

### Loader

Fabric

### Loader Version

Fabric 0.15.11

### API Version

fabric-api-0.92.0+1.20.1

### Mod Version

polymorph-fabric-0.49.5+1.20.1

**Comment by TheIllusiveC4** [comment]
I can't reproduce this bug, installing Simple Animated Guns and Croptopia I am able to to select either Plastic or Molasses as expected. It's odd because the default should be Plastic, but your post implies that your default is Molasses.

Can you try testing with _just_ Simple Animated Guns, Croptopia, and Polymorph installed and see if the issue still occurs?

**Comment by MrSickNSinister** [comment]
Yes I will I suspect it has something to do with some other mod i have installed in my modpack I will do some testing I disabled croptopia in version thats uploaded to curseforge or id say u could install it and see for yourself but that wont work
