### ISSUE TITLE
[1.15.2] Random crash whilst interacting with Crafting Table (FastWorkbench installed.)

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/Polymorph#3]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.15.2-0.1
* Forge: 31.2.9
#### Observed Behavior:
Random crash while interacting & crafting something with the Crafting Table. (Using FastWorkbench.)
#### Expected Behavior:
Not crashing whilst attempting to craft something.
#### Steps to Reproduce: (No idea how to reproduce because it happens at random times.)

Crash Log:  [Gist Github](https://gist.github.com/Gbergz/0e4e4f9a476ab2bfb230aa465c3e163c).

**Comment by Gbergz** [comment]
Sorry didn't see you released a 0.2 version, i'll get back to you when i've tried it.

**Comment by TheIllusiveC4** [comment]
You could try it out anyways, but I don't think the 0.2 version would help with this particular issue. I haven't seen this behavior at all, so it will be difficult to fix without a way to reproduce this reliably. Do you remember what you were trying to craft when it happened? Also, how frequently does this happen? If it happens fairly frequently, could you maybe try to reproduce this with only FastWorkbench and Polymorph and see if it ever crashes with just those two installed?

**Comment by Vaelzan** [comment]
It's an interaction with the fast shapeless recipe change that the Placebo mod adds. This can be disabled in the Placebo config but it is on but default. We've had several crash reports on the Valhelsia Discord since we updated to include Polymorph (essentially the same crash report as the one already posted).

**Comment by TheIllusiveC4** [comment]
@Vaelzan Do you know if there is any pattern in regards to what it is being crafted when the crash occurs?

**Comment by TheIllusiveC4** [comment]
I've added some error handling to prevent the crashing, which will mitigate the issue from a user perspective, although this bug will still be present. 

Instead of crashing, it will likely result in not displaying any recipe conflicts and their outputs (for that particular crafting instance). If anyone comes across this issue again in either form, please check your logs for any errors from Polymorph as well as note down the attempted recipe in your bug report. I need to be able to reproduce this somehow before I can make an attempt at a proper resolution.

**Comment by Vaelzan** [comment]
Apologies, nobody that has sent me a report so far has actually told me what they're crafting. If I see another report sent through I'll ask more questions.

**Comment by LlubNek** [comment]
here's a related bug report for Placebo:
https://github.com/Shadows-of-Fire/Placebo/issues/13

**Comment by LlubNek** [comment]
I'm not using the Valhesia modpack (though I am using their structure mod), but when it happens to me, it happens with (at least), crafting table->crafting station, log->planks, plank->button... It's probably all shapeless crafting recipes, and happens in both the inventory crafting grid and the crafting table.  There will be no output shown, but the crafting interface gets messed up after this bug manifests, so that even shaped recipes don't work right until the crafting interface is reopened.  This can also result in item duplication for ingredients left in the crafting grid.

**Comment by TheIllusiveC4** [comment]
@LlubNek Your bug report on Placebo seems to imply that the first error occurs even without Polymorph installed. Is that true, or do all of them only occur with Polymorph?

**Comment by Shadows-of-Fire** [comment]
The issue is probably not with Polymorph, the underlying issue is some mod adding some shapeless recipe with an ingredient that chokes when Ingredient#getValidItemStacksPacked is invoked.

The reason why polymorph makes it show up (more than usual, anyway) is that you're probably matching through all the recipes always to detect for conflicting ones, which makes this particular bad ingredient show up every instance of the table being changed.

I'll have to make some kind of debug version of placebo to reliably trace what mod is adding the bad ingredient (namely catching this crash and reporting the erroneous recipe).

**Comment by TheIllusiveC4** [comment]
Hmm okay, thanks a lot for the info Shadows-of-Fire, that makes a lot of sense.

I'll leave this issue open for the time being until the offending mod/recipe is discovered. In the meantime, I suggest everyone who is having this issue to use the jar referenced here https://github.com/Shadows-of-Fire/Placebo/issues/13#issuecomment-653702092 to try and determine the problem and report back here.

**Comment by LlubNek** [comment]
> @LlubNek Your bug report on Placebo seems to imply that the first error occurs even without Polymorph installed. Is that true, or do all of them only occur with Polymorph?

It's hard to say, I'm having trouble reproducing this bug when I want to.  I suspect the Placebo error does show up without Polymorph, but if nothing else happens then I have no reason to check the log whenever I craft something.

**Comment by Vaelzan** [comment]
I think I may have figured it out, at least enough to have more to go off of. I haven't verified this but it seems plausible:

FastUtil isn't thread safe. In at least one log that I was looking at, the server thread and the render thread appeared to be touching Ingredient.getValidItemStacksPacked at the same time - the server thread dealing with CClickWindowPacket processing and the render thread dealing with Polymorph code.

**Comment by TheIllusiveC4** [comment]
Hmm, very interesting. I'll have to look at this issue again with that in mind.

**Comment by Vaelzan** [comment]
:)

https://github.com/Shadows-of-Fire/Placebo/commit/a2ae1751d2d4cff16f8a05ba2857ab93267338c4

**Comment by TheIllusiveC4** [comment]
Oh ok, cool. Hopefully that solves the issue. I'll mark this as closed for now, but let me know if the issue persists.

**Comment by LlubNek** [comment]
not fixed...
see https://github.com/Shadows-of-Fire/Placebo/issues/13#issuecomment-653836423
