### ISSUE TITLE
Help Needed Fixing Compat With My Mod Crumbs

### ISSUE THREAD

**Issue by Trikzon** [TheIllusiveC4/Polymorph#47]
#### Versions:

* Polymorph: 1.16.4-0.20
* Forge/Fabric: forge (possibly also fabric)
* Crumbs: 1.0.5+1.16.4

#### Observed Behavior:

Opening a Crumbs Crafting Table crashes the game.

#### Expected Behavior:

Right clicking on a Crumbs Crafting Table should open the CrumbsCraftingMenu which extends the vanilla menu.

#### Steps to Reproduce:
1. Install polymorph and crumbs.
2. Place a crumbs crafting table (spruce for example).
3. Right click the crafting table.
...

Crash Log: https://gist.github.com/Trikzon/df5316e256e6165c83de07770f031037.

---

#### Other Information:

My mod adds new crafting table blocks that only change the menu (I think this is called a container in non-mojmaps) of the crafting table to allow the menu to stay valid and stay open.

Block: https://github.com/dodogang/crumbs/blob/1.16.4/common/src/main/java/net/dodogang/crumbs/block/CrumbsCraftingTableBlock.java
Menu: https://github.com/dodogang/crumbs/blob/1.16.4/common/src/main/java/net/dodogang/crumbs/menu/CrumbsCraftingMenu.java

Without polymorph, this works fine. I can't easily tell what in polymorph is causing this, so hopefully, someone who is familiar with polymorph's code base can let me know.
I'm not sure if polymorph needs to add support for crumbs, or vice-versa.

**Comment by TheIllusiveC4** [comment]
I was a little confused at first as Polymorph is not even called anywhere in the stacktrace and I had a hard time figuring out what could have caused this on my end. However, I just tested an instance with only Crumbs installed and it resulted in the same crash, so this is not a Polymorph compatibility issue. For your reference, I was using only Crumbs 1.0.5 and Forge 35.1.13 on MultiMC.

Here's the crash log so that you can verify that the cause is the same and that Polymorph is not loaded:
https://pastebin.com/N9E6GUUJ

**Comment by Trikzon** [comment]
Hmm ok, now I'm more confused than before because I didn't get the crash when I tried it without polymorph installed.
Thanks for letting me know its on my end, I'll fix it myself in that case.
