### ISSUE TITLE
Crafting output missing in RS Pattern Grid

### ISSUE THREAD

**Issue by Darkere** [TheIllusiveC4/Polymorph#56]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.4-0.22.jar
* Forge/Fabric: Forge 
#### Observed Behavior:
Polymorph causes the crafting output in the Pattern grid to disappear sometimes

I'm unable to reproduce it after removing Polymorph.
#### Steps to Reproduce:
https://gfycat.com/ShadowyTastyFowl

I have Industrial forgoing installed as switching between the range addon recipes and a crafting recipes makes the problem more common. 

I'm unsure what could be causing it. I haven't looked at the polymorph code just yet though :)

Link to original report: https://github.com/refinedmods/refinedstorage/issues/2814

**Comment by TheIllusiveC4** [comment]
After looking into it, this is probably symptomatic of a deeper syncing issue within Polymorph. However, that'll take some time to properly implement a solution so I've written a stopgap solution that should address this specific problem. I can't 100% guarantee that it does since this problem cannot be reproduced 100% of the time, but the problem seems to have disappeared in my testing after many attempts. Please let me know if this is not the case and I'll re-open this issue.
