### ISSUE TITLE
Allows Vanilla Recipes on Modded Furnace Even Though Disabled

### ISSUE THREAD

**Issue by czbuendel** [TheIllusiveC4/Polymorph#63]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.16.5-0.24
* Forge/Fabric: 36.0.14
#### Steps to Reproduce:
1. Setup new instance with Brick Furnace and Polymorph
2. Change brickfurnace-server.toml in a created world serverconfig folder value "vanillaRecipesEnabled = true" to false
3. Enter world and use Brick Furnace to smelt anything, even though it shouldn't.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
No Crash

**Comment by TheIllusiveC4** [comment]
You mentioned the Kiln from Charm Reforged. How does that one work?

**Comment by czbuendel** [comment]
That one acts similiarly, So in a pack with say Charm, Polymorph, and Vanilla Food Pantry the Kiln can cook an egg even though that shouldn't be possible. Disabling Polymorph, it won't cook them.

**Comment by TheIllusiveC4** [comment]
Hmm, so I've managed to fix the issue in my development build with the Kiln from Charm Reforged, that was pretty straightforward. However, the Brick Furnace from Brick Furnace is a little trickier due to how they've set up dual recipe types. I'm currently not sure what the best solution is, so I'll have to think on that some more.

**Comment by TheIllusiveC4** [comment]
This should be fixed as of version 1.16.5-0.26. If that is not the case, please let me know.
