### ISSUE TITLE
Polymorph button doesn't show

### ISSUE THREAD

**Issue by dwiantlake** [TheIllusiveC4/Polymorph#66]
I have Quark installed on my personal modpack and it made some variant to the chest, althou the chest cannot be combine into the large variant if they have different material, even with this mod installed it still doesn't show that I can change the chest into normal one like in any other modpacks.
Is there any way or config to change that?
TY.

**Comment by TheIllusiveC4** [comment]
This is because Quark normally disables the regular recipe. That's why it doesn't show up. Modpacks sometimes re-add the recipe themselves and that's what you would need to do. Although do note that Quark has a special recipe that gives you the normal chest if you mix materials in the crafting grid.
