### ISSUE TITLE
Recipe output flickers while you using a crafting station

### ISSUE THREAD

**Issue by thecatking9274** [TheIllusiveC4/Polymorph#82]
#### Versions (Be specific, do not write "latest"): 1.16.5
* Polymorph: almost everything
* Forge/Fabric: forge
#### Steps to Reproduce:
1. Download “improvement stations” mod
2. Craft a improved crafting station
3. Try polymorphing stuff
3. And it probably flicker
…

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Kore-Development** [comment]
This also happens on Fabric

**Comment by Kore-Development** [comment]
Here's the mod
Fabric: https://www.curseforge.com/minecraft/mc-mods/improved-stations
Forge: https://www.curseforge.com/minecraft/mc-mods/improved-stations-forge

**Comment by frakier** [comment]
Makes the game almost unplayable if any lag is introduced... and gets worse over time.
Eventually you have to blindly trust that it is making the correct thing and either drag out the completed item or do the other where the newly made item[s] go straight into inventory.. then close inventory and open to see if it made because it will not show up until you close... when you try to fill the recipe pattern it freaks out and your never sure if you have the right recipe until you look to see if it is flashing in the completed are. Never sure if you are dragging the correct item or a ghost item. Everyone on the server is having the same problems.
forge: 36.2.8
polymorph: 1.16.5-0.25 
modpack: Valhelsia 3 - 3.4.4

**Comment by TheIllusiveC4** [comment]
Improved Stations support has been added in version 1.16.5-0.26 on Forge, and I believe this issue has been resolved on the Fabric version as well since 0.11-1.16.5. Please let me know if this is not the case.
