### ISSUE TITLE
Incompatible with Recipe Cache

### ISSUE THREAD

**Issue by SplendidAlakey** [TheIllusiveC4/Polymorph#96]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-fabric-0.0.14-1.17.1
* Forge/Fabric: fabric-api-0.40.1+1.17
#### Observed Behavior: 

When [Recipe Cache](https://www.curseforge.com/minecraft/mc-mods/recipe-cache) is used alongside Polymorph, the recipe selection button does not appear.

I'd imagine it's the same issue as #92.

**Comment by TheIllusiveC4** [comment]
Unfortunately, due to the way Recipe Cache is coded, integration is not currently feasible. It's a bit different than FastBench, particularly in the fact that all of their logic is inside their own mixins which makes it impossible for me to target them.

I've opened up an issue about this on the Recipe Cache repository if you'd like to follow any updates on their end:
https://gitlab.com/biom4st3r/optimizedcrafting/-/issues/4

I'll update this thread as well once I've received a response to see how I'll move forward.

**Comment by TheIllusiveC4** [comment]
This compatibility is now working as of Polymorph 0.15-1.17.1+.
